namespace ATG.Voice
{
    public enum VoiceType: ushort
    {
        None = 0,
        Onboard = 1,
        SecondLocationWelcome = 2,
        GoToAltar = 3,
        SecondLocationAboutAltarInventory = 4,
        GoToGetLopatka = 5,
        Complete2Location = 6,
        ThirdLocationWelcome = 7,
        GoToGraniteTable = 8,
        ThirdLocationAbout = 9,
        GetSerdolitePlastine = 10,
        PolyshSerdolitePlastine = 11,
        PlacePlastineToTriplanatSkull = 12,
        Scene3Congratulation = 13,
        FourthLocationWelcome = 14,
        AboutFourthLocationQuest = 15,
        GetAndDropPowderPiles = 16,
        SmoothPowderPiles = 17,
        Scene4Congratulation = 18,
        FiveLocationWelcome = 19,
        DeformGoldLenta = 20,
        PlaceIvoryTooth = 21,
        PlaceGoldenLenta = 22,
        FixByNails = 23,
        Scene5Congratulation = 24,
        KnightAboutPain = 25,
        KnightFeelBetter = 26,
        KnightLikeWine = 27,
        SixLocationWelcome = 28,
        SixLevelLocationQuest = 29,
        RemoveToothByForcepts = 30,
        GrabWineMug = 31,
        Scene8Congratulation = 32,
        NineLocationWelcome1 = 33,
        NineLocationWelcome2 = 34,
        CutWire = 35,
        CutWireBySixPart = 36,
        DeformWireParts = 37,
        PlaceEngle1 = 38,
        PlaceEngle2 = 39,
        Scene9Congratulation = 40,
        PlaceEngle3 = 41
    }
}